language: swift
osx_image: xcode8
rvm:
  - 2.2.2
before_install:
  - gem install cocoapods
install:
  - pod install
script:
  - xcodebuild test -workspace SwiftAnnuity.xcworkspace -scheme SwiftAnnuity -destination 'name=iPhone 6'
  - pod lib lint
  - pod spec lint
after_success:
  - pod trunk push SwiftAnnuity.podspec
